// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabaseUrl, supabasePublishableKey } from './supabaseClient';

export const supabase = createClient<Database>(supabaseUrl!, supabasePublishableKey!, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
