// ─────────────────────────────────────────────────────────────────────────────
// GENERATED FILE — DO NOT EDIT BY HAND.
//
// This file is generated by the Supabase CLI from the live database schema.
// After applying any new migration in `supabase/migrations/`, regenerate it
// with (project id from `supabase/config.toml`):
//
//   npx supabase gen types typescript --project-id tmbnawwkqchswhsuetsl > src/integrations/supabase/types.ts
//
// (For a locally running stack, use `npx supabase gen types typescript --local`
// instead.)
//
// Last regenerated to match the migration snapshot in `supabase/migrations/`,
// including the gamification tables (badges, challenges, user_badges,
// user_challenges, mood_logs), the `award_user_xp()` function, and the
// `search_tokens` columns added for searchable encryption.
// ─────────────────────────────────────────────────────────────────────────────

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      chat_sessions: {
        Row: {
          created_at: string | null
          id: string
          messages: Json
          title: string | null
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          messages?: Json
          title?: string | null
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          messages?: Json
          title?: string | null
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      health_metrics: {
        Row: {
          created_at: string | null
          id: string
          metric_type: string
          notes: string | null
          recorded_at: string | null
          search_tokens: string[] | null
          user_id: string
          value: Json
        }
        Insert: {
          created_at?: string | null
          id?: string
          metric_type: string
          notes?: string | null
          recorded_at?: string | null
          search_tokens?: string[] | null
          user_id: string
          value: Json
        }
        Update: {
          created_at?: string | null
          id?: string
          metric_type?: string
          notes?: string | null
          recorded_at?: string | null
          search_tokens?: string[] | null
          user_id?: string
          value?: Json
        }
        Relationships: []
      }
      profiles: {
        Row: {
          allergies: string | null
          blood_type: string | null
          chronic_conditions: string | null
          created_at: string | null
          date_of_birth: string | null
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          full_name: string | null
          gender: string | null
          id: string
          updated_at: string | null
          user_id: string
          xp: number
          level: number
          encryption_salt: string | null
          community_opt_in?: boolean | null
          community_visible?: boolean | null
        }
        Insert: {
          allergies?: string | null
          blood_type?: string | null
          chronic_conditions?: string | null
          created_at?: string | null
          date_of_birth?: string | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          full_name?: string | null
          gender?: string | null
          id?: string
          updated_at?: string | null
          user_id: string
          xp?: number
          level?: number
          encryption_salt?: string | null
          community_opt_in?: boolean | null
          community_visible?: boolean | null
        }
        Update: {
          allergies?: string | null
          blood_type?: string | null
          chronic_conditions?: string | null
          created_at?: string | null
          date_of_birth?: string | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          full_name?: string | null
          gender?: string | null
          id?: string
          updated_at?: string | null
          user_id?: string
          xp?: number
          level?: number
          encryption_salt?: string | null
          community_opt_in?: boolean | null
          community_visible?: boolean | null
        }
        Relationships: []
      }
      groups: {
        Row: {
          id: string
          name: string
          description: string | null
          topic: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          topic: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          topic?: string
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      group_members: {
        Row: {
          id: string
          user_id: string
          group_id: string
          anonymous_alias: string
          joined_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          group_id: string
          anonymous_alias: string
          joined_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          group_id?: string
          anonymous_alias?: string
          joined_at?: string | null
        }
        Relationships: []
      }
      group_posts: {
        Row: {
          id: string
          user_id: string
          group_id: string
          content: string
          post_type: 'achievement' | 'question'
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          group_id: string
          content: string
          post_type: 'achievement' | 'question'
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          group_id?: string
          content?: string
          post_type?: 'achievement' | 'question'
          created_at?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      reported_posts: {
        Row: {
          id: string
          post_id: string
          reporter_id: string
          reason: string
          status: string
          created_at: string | null
        }
        Insert: {
          id?: string
          post_id: string
          reporter_id: string
          reason: string
          status?: string
          created_at?: string | null
        }
        Update: {
          id?: string
          post_id?: string
          reporter_id?: string
          reason?: string
          status?: string
          created_at?: string | null
        }
        Relationships: []
      }
      symptom_history: {
        Row: {
          ai_analysis: string
          created_at: string | null
          follow_up_date: string | null
          id: string
          possible_causes: string[] | null
          recommendations: string[] | null
          resolved: boolean | null
          risk_score: number | null
          search_tokens: string[] | null
          severity_level: string
          symptoms: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          ai_analysis?: string
          created_at?: string | null
          follow_up_date?: string | null
          id?: string
          possible_causes?: string[] | null
          recommendations?: string[] | null
          resolved?: boolean | null
          risk_score?: number | null
          search_tokens?: string[] | null
          severity_level: string
          symptoms: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          ai_analysis?: string
          created_at?: string | null
          follow_up_date?: string | null
          id?: string
          possible_causes?: string[] | null
          recommendations?: string[] | null
          resolved?: boolean | null
          risk_score?: number | null
          search_tokens?: string[] | null
          severity_level?: string
          symptoms?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      badges: {
        Row: {
          condition_type: string
          condition_value: number
          created_at: string
          description: string | null
          icon: string | null
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          condition_type: string
          condition_value: number
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          condition_type?: string
          condition_value?: number
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      challenges: {
        Row: {
          category: string
          color: string | null
          created_at: string
          description: string | null
          duration_days: number
          icon: string | null
          id: string
          target_value: number
          title: string
          unit: string
          updated_at: string
        }
        Insert: {
          category: string
          color?: string | null
          created_at?: string
          description?: string | null
          duration_days: number
          icon?: string | null
          id?: string
          target_value: number
          title: string
          unit: string
          updated_at?: string
        }
        Update: {
          category?: string
          color?: string | null
          created_at?: string
          description?: string | null
          duration_days?: number
          icon?: string | null
          id?: string
          target_value?: number
          title?: string
          unit?: string
          updated_at?: string
        }
        Relationships: []
      }
      mood_logs: {
        Row: {
          created_at: string
          id: string
          logged_at: string
          mood: string
          note: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          logged_at: string
          mood: string
          note?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          logged_at?: string
          mood?: string
          note?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mood_logs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      user_badges: {
        Row: {
          badge_id: string
          created_at: string
          earned_at: string
          id: string
          user_id: string
        }
        Insert: {
          badge_id: string
          created_at?: string
          earned_at?: string
          id?: string
          user_id: string
        }
        Update: {
          badge_id?: string
          created_at?: string
          earned_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_badges_badge_id_fkey"
            columns: ["badge_id"]
            isOneToOne: false
            referencedRelation: "badges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_badges_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      user_challenges: {
        Row: {
          best_streak: number
          challenge_id: string
          completed_at: string | null
          created_at: string
          id: string
          last_checked_in: string | null
          started_at: string
          status: string
          streak_count: number
          updated_at: string
          user_id: string
        }
        Insert: {
          best_streak?: number
          challenge_id: string
          completed_at?: string | null
          created_at?: string
          id?: string
          last_checked_in?: string | null
          started_at?: string
          status?: string
          streak_count?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          best_streak?: number
          challenge_id?: string
          completed_at?: string | null
          created_at?: string
          id?: string
          last_checked_in?: string | null
          started_at?: string
          status?: string
          streak_count?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_challenges_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "challenges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_challenges_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      award_user_xp: {
        Args: {
          points_to_add: number
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
